// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOxv2L6oBnONCWhPV6J6yjfmqIuLjtTDg',
    appId: '1:205321384573:web:36a87c126117fa7feab714',
    messagingSenderId: '205321384573',
    projectId: 'fbui-7afd3',
    authDomain: 'fbui-7afd3.firebaseapp.com',
    storageBucket: 'fbui-7afd3.firebasestorage.app',
    measurementId: 'G-T1L0D27C4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_tTsfsrCI8VEdkiuC7R77NVNSG3ePEqA',
    appId: '1:205321384573:android:6642af3eb0d1b0b7eab714',
    messagingSenderId: '205321384573',
    projectId: 'fbui-7afd3',
    storageBucket: 'fbui-7afd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_zV04cQx3oeqrfubrWK9OfGnQo2eHFLw',
    appId: '1:205321384573:ios:e3e105294317e5c5eab714',
    messagingSenderId: '205321384573',
    projectId: 'fbui-7afd3',
    storageBucket: 'fbui-7afd3.firebasestorage.app',
    iosBundleId: 'com.example.fbUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOxv2L6oBnONCWhPV6J6yjfmqIuLjtTDg',
    appId: '1:205321384573:web:4b076cb58fcb3218eab714',
    messagingSenderId: '205321384573',
    projectId: 'fbui-7afd3',
    authDomain: 'fbui-7afd3.firebaseapp.com',
    storageBucket: 'fbui-7afd3.firebasestorage.app',
    measurementId: 'G-JC4PVPT5MS',
  );

}